## Data Filtering and Selection

In [2]:
!pip install numpy
!pip install pandas

Requirement already satisfied: numpy in /home/codespace/.local/lib/python3.10/site-packages (1.26.1)

[notice] A new release of pip is available: 23.3 -> 23.3.1
[notice] To update, run: python -m pip install --upgrade pip
Requirement already satisfied: pandas in /home/codespace/.local/lib/python3.10/site-packages (2.1.1)
Requirement already satisfied: numpy>=1.22.4 in /home/codespace/.local/lib/python3.10/site-packages (from pandas) (1.26.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.10/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /home/codespace/.local/lib/python3.10/site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /home/codespace/.local/lib/python3.10/site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

[notice] A new release of pip is available: 23.3 -> 23.3.1
[notice] To update, run: python -m pip install --upgrade pip

In [3]:
import numpy as np
import pandas as pd

from pandas import DataFrame

In [13]:
numbers_df = DataFrame(np.arange(0,90,3).reshape(10,3), index = ['row 1','row 2','row 3','row 4','row 5','row 6','row 7','row 8','row 9','row 10'],columns=['column 1','column 2','column 3'])
numbers_df

        column 1  column 2  column 3
row 1          0         3         6
row 2          9        12        15
row 3         18        21        24
row 4         27        30        33
row 5         36        39        42
row 6         45        48        51
row 7         54        57        60
row 8         63        66        69
row 9         72        75        78
row 10        81        84        87

#### Comparison operators (> < = <= => == !=) and Masking.

In [ ]:
# %% [markdown]
# ## Working with Missing Data in Pandas

# %%
import numpy as np
import pandas as pd

from pandas import DataFrame

# %% [markdown]
# ### Filling missing values using fillna(), replace() and interpolate()

# %%
data = {'names': ['steve','john','richard','sarah','randy','michael','julie'],
        'age':[20,22,20,21,24,23,22],
        'gender': ['Male','Male','Male','Female','Male','Male','Female'],
        'rank':[2,1,4,5,3,7,6]}

ranking_df = DataFrame(data)
ranking_df.iloc[2:5,1] = np.nan
ranking_df.iloc[3:6,3] = np.nan
ranking_df.iloc[3,:] = np.nan
ranking_df

# %%
ranking_df.isnull()

# %%
ranking_df.notnull()

# %%
bool_series = pd.isnull(ranking_df['age'])
ranking_df[bool_series]

# %%
ranking_df.fillna(0) #fill nan with static number

# %%
ranking_df.fillna(method='pad') #fill nan with previous valid entry

# %%
ranking_df.fillna(method='bfill') #fill nan with next valid entry

# %%
ranking_df.interpolate(method='linear') #fill in nan with decimal 
#numbers in linear steps

# %%
ranking_df.dropna() #drop all rows containing a nan

# %%
ranking_df.dropna(how='all') #drop rows with all nan

# %%
ranking_df.dropna(axis=1) #all columns with missing values

# %%
ranking_df.dropna(axis = 0) #drops rows with missing values